### ISSUE TITLE
NPE analyzing large exe with Windows/VS RTTI

### ISSUE THREAD

**Issue by FallenAvatar** [astrelsky/Ghidra-Cpp-Class-Analyzer#19]
I have run all other analysis tools. This error happens in one-shot mode, as well as, as part of auto analysis. I have tried with and without "Locate Constructors".

Exception throw:

```
Analysis Task: Windows C++ Class Analyzer - 
java.lang.NullPointerException
	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.wrappers.WindowsVtableModel.getVbtableBuffer(WindowsVtableModel.java:51)
	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.wrappers.WindowsVtableModel.<init>(WindowsVtableModel.java:42)
	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.wrappers.RttiModelWrapper.doGetVtable(RttiModelWrapper.java:374)
	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.wrappers.RttiModelWrapper.<init>(RttiModelWrapper.java:156)
	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.wrappers.RttiModelWrapper.getWrapper(RttiModelWrapper.java:116)
	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.windows.WindowsCppClassAnalyzer.getClassTypeInfoList(WindowsCppClassAnalyzer.java:97)
	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.windows.WindowsCppClassAnalyzer.getClassTypeInfoList(WindowsCppClassAnalyzer.java:115)
	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.AbstractCppClassAnalyzer.added(AbstractCppClassAnalyzer.java:98)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:185)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:62)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:832)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: C:\Program Files\AdoptOpenJDK\jdk-14.0.1.7-hotspot
JVM Version: AdoptOpenJDK 14.0.1
OS: Windows 10 10.0 amd64
Workstation: AmysRig
```

Let me know what else you might need.

**Comment by astrelsky** [comment]
@FallenAvatar I have a massive set of changes coming within the next week. Hopefully this will be resolved with the incoming changes.

**Comment by FallenAvatar** [comment]
@astrelsky  Awesome. I will test and update this issue as soon as you release it.

**Comment by FallenAvatar** [comment]
Any news?

**Comment by astrelsky** [comment]
> Any news?

Still working on it. I put up an experimental branch a week ago I think. I'm changing the constructor analysis to use the decompiler instead for better accuracy and less false positives. I haven't changed the windows constructor analyzer to use this new approach yet. I hope to get to it by the end of the week.

**Comment by FallenAvatar** [comment]
I am using Ghirda 9.2. If you provide a built plugin I would be happy to do some testing.

**Comment by astrelsky** [comment]
> I am using Ghirda 9.2. If you provide a built plugin I would be happy to do some testing.

I just did a quick check with what I have on a VS binary and it seems I have a handful of things to fix first. Most of the new gui elements are not functional atm. Once I have it in a more stable state again I will put up a build.

**Comment by astrelsky** [comment]
@FallenAvatar please give the experimental build a shot https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/releases/tag/2.0-alpha. If you have any problems please let me know.

**Comment by FallenAvatar** [comment]
I'm sorry, I thought I had 9.2, i currently have 9.1.2. I will be looking into setting up a 9.2 as soon as i have time.

**Comment by FallenAvatar** [comment]
Ok, got that up and running faster than I thought. Hit an error pretty quickly unfortunately.

> Analysis Task: Windows C++ Class Analyzer - One Time - Ghidra-Cpp-Class-Analyzer: failed to wrap .?AV?$hkSingleton@VhkReferencedObjectLock@@@@
> ghidra.util.exception.AssertException: Ghidra-Cpp-Class-Analyzer: failed to wrap .?AV?$hkSingleton@VhkReferencedObjectLock@@@@
> 	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.wrappers.RttiModelWrapper.getWrapper(RttiModelWrapper.java:101)
> 	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.windows.WindowsCppClassAnalyzer.buildClassTypeInfoDatabase(WindowsCppClassAnalyzer.java:131)
> 	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.windows.WindowsCppClassAnalyzer.added(WindowsCppClassAnalyzer.java:68)
> 	at ghidra.app.plugin.core.analysis.OneShotAnalysisCommand.applyTo(OneShotAnalysisCommand.java:47)
> 	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
> 	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
> 	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
> 	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
> 	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
> 	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
> 	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
> ---------------------------------------------------
> Build Date: 2020-Jul-06 0222 EDT
> Ghidra Version: 9.2
> Java Home: C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot
> JVM Version: AdoptOpenJDK 11.0.7
> OS: Windows 10 10.0 amd64
> Workstation: AmysRig

I will note that Ghidra's built in RTTI info finder did not have a good time of actually identifying all the RTTI info and properly linking it all up. Many, many classes have only one bit of info like a vftable, or only the CompleteObjectLocator even tho all the addresses in those structures point to the correct places.

Let me know if you need any more info.

**Comment by FallenAvatar** [comment]
I am trying to re-run the built-in RTTI analysis step, and will retry this plugin after.

**Comment by astrelsky** [comment]
> I am trying to re-run the built-in RTTI analysis step, and will retry this plugin after.
> 
> EDIT: Nope, exact same error.
> 
> Though looking into the error more, specifically in regards to this executable, it looks like Ghidra named the class "class_hkReferencedObjectLock" instead of "hkReferencedObjectLock"
> 
> EDIT2: And that isn't the issue. Fixed all the naming issues and as soon as I run this plugin the "class_" version reappears

I noticed this myself the other day. I have no idea why this was done and it makes no sense to do so.

Is this something you have the rights to share by any chance? I only ask because that is the easiest approach. If not it is understandable. I'm attaching another build. The only change here is I've appended the caught exception to the AssertException so that I'll know where it came from.

[ghidra_9.2_DEV_20200706_Ghidra-Cpp-Class-Analyzer.zip](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/files/4879201/ghidra_9.2_DEV_20200706_Ghidra-Cpp-Class-Analyzer.zip)

**Comment by FallenAvatar** [comment]
Ok, tested new version, here is the error:

> Analysis Task: Windows C++ Class Analyzer - One Time - 
> java.lang.NullPointerException
> 	at java.base/java.nio.ByteBuffer.wrap(ByteBuffer.java:422)
> 	at cppclassanalyzer.data.typeinfo.WindowsClassTypeInfoDB.<init>(WindowsClassTypeInfoDB.java:44)
> 	at cppclassanalyzer.data.manager.ClassTypeInfoManagerDB$WindowsRttiRecordWorker.buildType(ClassTypeInfoManagerDB.java:966)
> 	at cppclassanalyzer.data.manager.ClassTypeInfoManagerDB$WindowsRttiRecordWorker.buildType(ClassTypeInfoManagerDB.java:958)
> 	at cppclassanalyzer.data.manager.AbstractRttiRecordWorker.getType(AbstractRttiRecordWorker.java:209)
> 	at cppclassanalyzer.data.manager.AbstractRttiRecordWorker.resolve(AbstractRttiRecordWorker.java:157)
> 	at cppclassanalyzer.data.manager.ClassTypeInfoManagerDB.resolve(ClassTypeInfoManagerDB.java:469)
> 	at cppclassanalyzer.data.manager.ClassTypeInfoManagerDB.resolve(ClassTypeInfoManagerDB.java:66)
> 	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.windows.WindowsCppClassAnalyzer.buildClassTypeInfoDatabase(WindowsCppClassAnalyzer.java:133)
> 	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.windows.WindowsCppClassAnalyzer.added(WindowsCppClassAnalyzer.java:68)
> 	at ghidra.app.plugin.core.analysis.OneShotAnalysisCommand.applyTo(OneShotAnalysisCommand.java:47)
> 	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
> 	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
> 	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
> 	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
> 	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
> 	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
> 	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
> ---------------------------------------------------
> Build Date: 2020-Jul-06 0222 EDT
> Ghidra Version: 9.2
> Java Home: C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot
> JVM Version: AdoptOpenJDK 11.0.7
> OS: Windows 10 10.0 amd64
> Workstation: AmysRig

As for sending the binary, let me think on that...

Also, how hard is it to setup this plugin for dev? I already have eclipse and what not. If you let me know how to get started, I will happily dig into the plugin it self on my end.

**Comment by astrelsky** [comment]
> Ok, tested new version, here is the error:
> -snip-
> As for sending the binary, let me think on that...
> 
> Also, how hard is it to setup this plugin for dev? I already have eclipse and what not. If you let me know how to get started, I will happily dig into the plugin it self on my end.
> 
> EDIT: Also, I am getting similar errors when trying to save the file. Same exception type and location, but ghidra reports it during an event listener.

Ah that is due to a mishap with some of the record data. That might actually be hiding the underlying issue. There is a ghidra script "ResetDatabaseScript.java" go ahead and run that with the plugin disabled. It will only remove the database tables that the plugin created so it can start fresh.

I'm using vscode so the setup is a bit different from the usual plugin development. If you have the GhidraDev plugin then you should be able to just replace the `build.gradle` file with the default extension one and open the project in eclipse.

**Comment by FallenAvatar** [comment]
> Analysis Task: Windows C++ Class Analyzer - One Time - Ghidra-Cpp-Class-Analyzer: failed to wrap .?AV?$hkSingleton@VhkReferencedObjectLock@@@@
> ghidra.util.exception.AssertException: Ghidra-Cpp-Class-Analyzer: failed to wrap .?AV?$hkSingleton@VhkReferencedObjectLock@@@@
> 	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.wrappers.RttiModelWrapper.getWrapper(RttiModelWrapper.java:101)
> 	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.windows.WindowsCppClassAnalyzer.buildClassTypeInfoDatabase(WindowsCppClassAnalyzer.java:131)
> 	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.windows.WindowsCppClassAnalyzer.added(WindowsCppClassAnalyzer.java:68)
> 	at ghidra.app.plugin.core.analysis.OneShotAnalysisCommand.applyTo(OneShotAnalysisCommand.java:47)
> 	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
> 	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
> 	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
> 	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
> 	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
> 	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
> 	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: ghidra.program.model.data.InvalidDataTypeException: Invalid data type error.
> 	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.wrappers.RttiModelWrapper.isSetupComplete(RttiModelWrapper.java:157)
> 	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.wrappers.RttiModelWrapper.<init>(RttiModelWrapper.java:140)
> 	at ghidra.app.plugin.prototype.CppCodeAnalyzerPlugin.wrappers.RttiModelWrapper.getWrapper(RttiModelWrapper.java:97)
> 	... 11 more
> 
> ---------------------------------------------------
> Build Date: 2020-Jul-06 0222 EDT
> Ghidra Version: 9.2
> Java Home: C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot
> JVM Version: AdoptOpenJDK 11.0.7
> OS: Windows 10 10.0 amd64
> Workstation: AmysRig

**Comment by astrelsky** [comment]
I think RttiModelWrapper.getRtti3Model is returning null. I'm looking into how this could be.

**Comment by astrelsky** [comment]
@FallenAvatar does the ClassHierarchyDescriptor exist for `Singleton<ReferencedObjectLock>`?

**Comment by FallenAvatar** [comment]
the only one in there is:
> hkSingleton<hkReferencedObjectLock>::RTTI_Base_Class_Descriptor_at_(8,-1,0,64)

and hkSingleton<class_hkReferencedObjectLock> popped back up again, and yes just to be clear, the "hk" is part of the names.

**Comment by FallenAvatar** [comment]
Got a discord or anything so we can talk about this more easily? FallenAvatar28#6234

**Comment by astrelsky** [comment]
> the only one in there is:
> 
> > hkSingleton::RTTI_Base_Class_Descriptor_at_(8,-1,0,64)
> 
> and hkSingleton<class_hkReferencedObjectLock> popped back up again.

Ah this may be why, I'm relying on something that doesn't exist. I may need to come up with a way to work around this.

> There is a related label also:
> 
> > hkSingleton_RTTI_Type_Descriptor
> 
> Just to be clear, the "hk" is part of the names.

I eyeballed it.

**Comment by garyttierney** [comment]
Hi!

Just to report: I ran into the exact same problem and the release published just a few hours ago at https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/releases/tag/2.0-alpha.2 fixed it for me.

**Comment by FallenAvatar** [comment]
After some testing, I agree that this issue has been solved. :) Thanks again @astrelsky
