### ISSUE TITLE
Installation: Can't find plugin in experimental-configure

### ISSUE THREAD

**Issue by Zhxhh** [astrelsky/Ghidra-Cpp-Class-Analyzer#21]
Ghidra: 9.1.2 
OS: Windows10 
I have extract archive to folder in Ghidra/Extensions/Ghidra
![image](https://user-images.githubusercontent.com/32181911/89986811-ad1d7d80-dcaf-11ea-92d8-73742aacb16a.png)

Click the + icon
![image](https://user-images.githubusercontent.com/32181911/89986848-b9093f80-dcaf-11ea-821e-75ca0e753ecf.png)

But I can't find "ClassTypeInfoManagerPlugin" in CodeBrowser-file-configure ...->Experimental
![image](https://user-images.githubusercontent.com/32181911/89986532-46985f80-dcaf-11ea-9a0b-5f33dc7a5de7.png)

Please tell me how I can install successfully. Thanks in advance.

**Comment by astrelsky** [comment]
Unfortunately the experimental version only supports the development builds of Ghidra 9.2 at this time.

**Comment by Zhxhh** [comment]
> Unfortunately the experimental version only supports the development builds of Ghidra 9.2 at this time.
> 
> The latest stable release does not contain the plugin as it appears to be correctly installed. The class analyzers should be available in the Analyze menu if applicable to the opened program.

I installed the old version of this plugin named "ghidra_9.1.2_....._Analyzer" . Doesn't it support Ghidra 9.1.2 either?

**Comment by astrelsky** [comment]
> > Unfortunately the experimental version only supports the development builds of Ghidra 9.2 at this time.
> > The latest stable release does not contain the plugin as it appears to be correctly installed. The class analyzers should be available in the Analyze menu if applicable to the opened program.
> 
> I installed the old version of this plugin named "ghidra_9.1.2_....._Analyzer" . Doesn't it support Ghidra 9.1.2 either?

The older version does support ghidra 9.1.2 however the plugin is still experimental and is not present in that release. From your screenshots it does appear to be correctly installed. There should be new analyzers available and the presence of the `TypeInfo` datatype in the BuiltInTypes datatype manager.

**Comment by Zhxhh** [comment]
> > > Unfortunately the experimental version only supports the development builds of Ghidra 9.2 at this time.
> > > The latest stable release does not contain the plugin as it appears to be correctly installed. The class analyzers should be available in the Analyze menu if applicable to the opened program.
> > 
> > 
> > I installed the old version of this plugin named "ghidra_9.1.2_....._Analyzer" . Doesn't it support Ghidra 9.1.2 either?
> 
> The older version does support ghidra 9.1.2 however the plugin is still experimental and is not present in that release. From your screenshots it does appear to be correctly installed. There should be new analyzers available and the presence of the `TypeInfo` datatype in the BuiltInTypes datatype manager.

 Actually I just extract the archive into the plugin folder. I can't understand the "Complied" step and just skip it . So may I asked if I installed the wrong way?
![image](https://user-images.githubusercontent.com/32181911/90085668-21f1c580-dd4b-11ea-8dc7-286befa80654.png)
Thanks for your help!!!

**Comment by astrelsky** [comment]
![image](https://user-images.githubusercontent.com/32181911/89986848-b9093f80-dcaf-11ea-821e-75ca0e753ecf.png)

The above image shows that you have it installed correctly.

**Comment by bugproof** [comment]
> The older version does support ghidra 9.1.2 however the plugin is still experimental and is not present in that release. 

Can we  download ghidra 9.2 binaries anywhere?

**Comment by astrelsky** [comment]
> > The older version does support ghidra 9.1.2 however the plugin is still experimental and is not present in that release. 
> 
> Can we  download ghidra 9.2 binaries anywhere? I have the same problem, plugin is installed but can't use it.

You can get a copy [here](https://github.com/garyttierney/ghidra-batteries-included). Beware that it contains a ghidra pull request that has not yet been accepted that makes changes to the database. Because of this if you use that build any project you upgrade will not be compatible with any ghidra build that doesn't have that pull request.
