### ISSUE TITLE
Improve support for binaries without RTTI

### ISSUE THREAD

**Issue by jrmuizel** [astrelsky/Ghidra-Cpp-Class-Analyzer#30]
I'm not sure exactly what's all possible to do automatically vs manually. At a minimum it would be nice to be able to be able select a vtable in memory and have the vtable struct constructed based on the pointed to functions and their types.

**Comment by astrelsky** [comment]
If you just want the struct for virtual function calls you can use a ghidra script and set a key binding for it. Just select the function table and run your script to make it. It should only take a few lines of code.

**Comment by jrmuizel** [comment]
Can you point me at the part of `Ghidra-Cpp-Class-Analyzer` that does this thing as a guide for how to do it?

**Comment by astrelsky** [comment]
You don't need the plugin for it. I can break it down into steps for you. 

* clear the currentSelection in the listing
* create a PointerDataType.dataType for each pointer in the currentSelection and insert into a list
* for each pointer data use Data.getValue and cast it to Address.
* get the function at each address, creating if necessary. 
* use askString to get a CategoryPath and DataType name
* create a new StructureDataType woth the category path and name. Using a size of 0 is ok as it will grow.
* for each function create a FunctionDefinitionDataType from Function.getSignature.
* for each definition create a pointer.
* add each function pointer to your Structure.
* use DataTypeManager.resolve to add the new structure to the database.
