### ISSUE TITLE
Support for Ghidra 9.2.3

### ISSUE THREAD

**Issue by IridiumXOR** [astrelsky/Ghidra-Cpp-Class-Analyzer#38]
Ghidra 9.2.3 has changed something in build process and Ghidra-CPP-Class-Analyzer fails to compile against it

**Comment by astrelsky** [comment]
> Ghidra 9.2.3 has changed something in build process and Ghidra-CPP-Class-Analyzer fails to compile against it

Are you using a version of gradle >= 5 and < 7? Ghidra's extension building script is not compatible with gradle 7. I've fixed the issue on my end but until Ghidra's `buildExtension.gradle` is compatible there isn't anything I can do about it.

**Comment by IridiumXOR** [comment]
Sorry, you can close the issue. It was a problem with my gradle docker which has problems with Selinux. With a standard gradle toolchain it works :)

**Comment by astrelsky** [comment]
> Sorry, you can close the issue. It was a problem with my gradle docker which has problems with Selinux. With a standard gradle toolchain it works :)

Don't sweat it. I expect to see this happen a few times until support for gradle 7 is fixed in the Ghidra gradle scripts.
