### ISSUE TITLE
Gradle fails to build the project

### ISSUE THREAD

**Issue by cakarlen** [astrelsky/Ghidra-Cpp-Class-Analyzer#4]
System info:
Mac OSX Mojave (10.14.6)

Attached is my Ghidra application.properties and the error log of `gradle buildExtension`.
I have set `GHIDRA_INSTALL_DIR` to my Ghidra root directory and `extension.properties` is set to my current version.

Any help is appreciated, thanks.
[gradle_build_fail.txt](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/files/3785550/gradle_build_fail.txt)
[my_application_properties.txt](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/files/3785551/my_application_properties.txt)

**Comment by astrelsky** [comment]
> System info:
> Mac OSX Mojave (10.14.6)
> 
> Attached is my Ghidra application.properties and the error log of `gradle buildExtension`.
> I have set `GHIDRA_INSTALL_DIR` to my Ghidra root directory and `extension.properties` is set to my current version.
> 
> Any help is appreciated, thanks.
> [gradle_build_fail.txt](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/files/3785550/gradle_build_fail.txt)
> [my_application_properties.txt](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/files/3785551/my_application_properties.txt)

I spent the last 4.5 hours fighting this myself. I'm assuming you've recently updated to JDK 13.0.1? If so its a gradle issue. You can't get the latest [gradle release-candidate](https://gradle.org/release-candidate/) which has jdk 13 support.

**Comment by cakarlen** [comment]
That solved it. Thanks for the help

**Comment by astrelsky** [comment]
> That solved it. Thanks for the help

No problem.
