### ISSUE TITLE
Installing the plugin in HeadlessMode

### ISSUE THREAD

**Issue by HexRoman** [astrelsky/Ghidra-Cpp-Class-Analyzer#43]
How is it possible to install the plugin in the Headless Mode - meaning without the use of GUI for the installation?

**Comment by astrelsky** [comment]
> How is it possible to install the plugin in the Headless Mode - meaning without the use of GUI for the installation? 

I'm not 100% sure. I did recently make changes to allow it to work in headless mode though so it should be possible. Try extracting the plugin to the extensions folder. Either of the two locations should work `{ghidra_root}/Ghidra/Extensions` or the `.ghidra/{ghidra_version}/Extensions`. Paths are not fully accurate since this response came from my phone.

**Comment by HexRoman** [comment]
I tried it both in Unix and Windows and it doesn't work. it looks like the installation is partial - I am able to call:

`from cppclassanalyzer.utils import CppClassAnalyzerUtils`

but 

`CppClassAnalyzerUtils.getManager(currentProgram)`

Returns None.

Only if installing through the GUI, and through the dialog prompted by Ghidra: 

> "New extension plugins detected. Would you like to configure them?" 

it is fully installed.

I did it at 2.5 tag.

**Comment by astrelsky** [comment]
As a sanity check, what does `ghidra.util.SystemUtilities.isInHeadlessMode()` return? Here is the relevant code for getting the manager which depends on said result:
https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/blob/c712bc1f46ac59582e546d451b1afe0cccca15c6/src/main/java/cppclassanalyzer/utils/CppClassAnalyzerUtils.java#L139-L147

**Comment by HexRoman** [comment]
Yes, it returns True.

**Comment by astrelsky** [comment]
> Yes, it returns True.

This shouldn't be possible then. You confirmed that you are able to retrieve a manager for the same program in the GUI but not in headless mode? The only way for it to return null is if no `RttiManagerProvider` supports the program.

**Comment by HexRoman** [comment]
I suggest the following scenario to reproduce the issue (Windows machine):
1. Download and extract a fresh copy of Ghidra. 
2. Rename <home>\.ghidra to <home>\.ghidra_bup
3. Copy the plugin to <ghidra_home>\Ghidra\Extensions
4. Create the following script file:
 
```
from cppclassanalyzer.utils import CppClassAnalyzerUtils
 
CppClassAnalyzerUtils.getManager(currentProgram).getTypeCount()
```
5. Save the file in <home>\script.py
6. Run the following from the command line:
`<ghidra_home>\support\analyzeHeadless <home> myproject -import <path_to_any_file>  -overwrite  -postscript <home>\script.py`
7. You will see in the console output:
```
Traceback (most recent call last):
  File <home>\script.py, line 14, in <module>
    CppClassAnalyzerUtils.getManager(currentProgram).getTypeCount()
AttributeError: 'NoneType' object has no attribute 'getTypeCount'
```

**Comment by HexRoman** [comment]
If I install it once from the GUI - it will work afterward from the Headless mode too. But without GUI it never works.

**Comment by astrelsky** [comment]
I will take a look tonight to see what is going on. This shouldn't be occurring.
