### ISSUE TITLE
Plugin doesn't appear in Configure->Experimental Plugins

### ISSUE THREAD

**Issue by tokyis** [astrelsky/Ghidra-Cpp-Class-Analyzer#44]
The extension (v10.0.3) downloaded from release, is added and checked in the list of installed extensions.
In the Code Browser, however, going to Configure -> Experimental, `ClassTypeInfoManagerPlugin` isn't showing up.

Ghidra v10.0.3 PUBLIC on Windows 10

**Comment by astrelsky** [comment]
> The extension (v10.0.3) downloaded from release, is added and checked in the list of installed extensions.
> In the Code Browser, however, going to Configure -> Experimental, `ClassTypeInfoManagerPlugin` isn't showing up.
> 
> Ghidra v10.0.3 PUBLIC on Windows 10

Hmm. That is strange. May you attach the `application.log` file? It will be located in `%HOMEPATH%\.ghidra\.ghidra_10.0.3_PUBLIC`.

**Comment by tokyis** [comment]
Installing the extension, restarting, creating a project, opening the CodeBrowser then checking Configure -> Experimental :
[application.log](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/files/7165547/application.log)

It's surprisingly quiet for such a complex tool, I didn't find any verbose mode in the doc either.

**Comment by astrelsky** [comment]
> Installing the extension, restarting, creating a project, opening the CodeBrowser then checking Configure -> Experimental :
> [application.log](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/files/7165547/application.log)
> 
> It's surprisingly quiet for such a complex tool, I didn't find any verbose mode in the doc either.

Yea there is a way to turn it on. It is very, very noisy though.

In the file `%GHIDRA_INSTALL_DIR%/support/debug.log4j.xml` change every level attribute to `TRACE`. Then in the `launch.properties` file in the support directory add `VMARGS=-Dlog4j.configuration=%GHIDRA_INSTALL_DIR%\support\debug.log4j.xml`. I recommend hard coding the path instead of relying on path expansion. You'll know when the configuration is loaded because there will be a ton of noise. Please send the noisy log file and hopefully something obvious is going wrong during static initialization or something.

**Comment by tokyis** [comment]
There you go, ALL worked :
[application.log](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/files/7166243/application.log)

**Comment by astrelsky** [comment]
> There you go, `ALL` worked :
> [application.log](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/files/7166243/application.log)
> 
> That looks suspicious :
> `2021-09-15 04:15:41 TRACE ghidra.util.classfinder.ClassFinder Ignoring jar file: C:\Users\kyis\.ghidra\.ghidra_10.0.3_PUBLIC\Extensions\ghidra_10.0.3_PUBLIC_20210909_Ghidra-Cpp-Class-Analyzer\lib\Ghidra-Cpp-Class-Analyzer.jar  `

Thank you. Yes, that looks very suspicious indeed. I will take a look at the log after work this afternoon.

Umm. I'm not sure if it even matters or why it ended up being named that way but try changing the folder name in Extensions from `ghidra_10.0.3_PUBLIC_20210909_Ghidra-Cpp-Class-Analyzer` to `Ghidra-Cpp-Class-Analyzer`. If that does fix it I'd like a bug report to be opened in the Ghidra repo especially if it was extracted automatically by the plugin installer ui.

**Comment by tokyis** [comment]
> > There you go, `ALL` worked :
> > [application.log](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/files/7166243/application.log)
> > That looks suspicious :
> > `2021-09-15 04:15:41 TRACE ghidra.util.classfinder.ClassFinder Ignoring jar file: C:\Users\kyis\.ghidra\.ghidra_10.0.3_PUBLIC\Extensions\ghidra_10.0.3_PUBLIC_20210909_Ghidra-Cpp-Class-Analyzer\lib\Ghidra-Cpp-Class-Analyzer.jar  `
> 
> Thank you. Yes, that looks very suspicious indeed. I will take a look at the log after work this afternoon.
> 
> Umm. I'm not sure if it even matters or why it ended up being named that way but try changing the folder name in Extensions from `ghidra_10.0.3_PUBLIC_20210909_Ghidra-Cpp-Class-Analyzer` to `Ghidra-Cpp-Class-Analyzer`. If that does fix it I'd like a bug report to be opened in the Ghidra repo especially if it was extracted automatically by the plugin installer ui.

That worked, Ghidra seems to have extracted it using the archive name, discarding the root folder, instead of extracting as is.

Thank you very much for your help. 👍

**Comment by astrelsky** [comment]
Great. May you please open an issue in the Ghidra repo regarding this?
