### ISSUE TITLE
Build Failed During Task: complieJava

### ISSUE THREAD

**Issue by richcfno1** [astrelsky/Ghidra-Cpp-Class-Analyzer#47]
ERROR: Cannot find method hasFlexibleArrayComponent()
if (((Structure) type.getDataType()).hasFlexibleArrayComponent()) {
                                                       ^

Note:
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

Thanks for your help!

**Comment by astrelsky** [comment]
Change to the dev branch for 10.1_BETA. Once it moves out of beta I'll move it into master.

I haven't thoroughly tested those changes so if you run into any issues let me know.

**Comment by richcfno1** [comment]
> Change to the dev branch for 10.1_BETA. Once it moves out of beta I'll move it into master.
> 
> I haven't thoroughly tested those changes so if you run into any issues let me know.

Thanks! I built it successfully, but when I tried to install it in Ghidra, it said:

Extension version for [Ghidra-Cpp-Class-Analyzer-dev] is incompatible with Ghidra.
---------------------------------------------------
Build Date: 2021-Nov-16 1948 EST
Ghidra Version: 10.1-BETA
Java Home: C:\Program Files\Java\jdk-17.0.1
JVM Version: Oracle Corporation 17.0.1
OS: Windows 10 10.0 amd64
Workstation: 128.113.17.98

**Comment by astrelsky** [comment]
Ah, Ghidra has this weird thing with naming requirements. If you remove the `-dev` from the zip file and the inner folder, or just remove the `-dev` from the work folder and rebuild, it should install.

**Comment by richcfno1** [comment]
> 

Hummm, same error again after I removed "-dev" and rebuild it.

**Comment by astrelsky** [comment]
> > 
> 
> Hummm, same error again after I removed "-dev" and rebuild it.

In the built zip file's `extension.properties` what is the value that was populated here?
https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/blob/17e871476edccbaa58f1dd48d890240f1d5fb89c/extension.properties#L5

**Comment by richcfno1** [comment]
> 

It is "version=@extversion@ "

**Comment by astrelsky** [comment]
> > 
> 
> It is "version=@extversion@ "

That shouldn't be. It should be changed to `version=10.1-BETA` during the build process. I'm not sure why it wasn't as I can see it was in the [pre release for 10.1_BETA](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/releases/tag/2.0.5.1)
