### ISSUE TITLE
Absolute path for docs in build script

### ISSUE THREAD

**Issue by v-p-b** [astrelsky/Ghidra-Cpp-Class-Analyzer#5]
I'm no gradle expert, but this line seems to make the build system create a directory on the root filesystem (on *nix), that usually results in a permission error:

https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/blob/master/build.gradle#L64

Can be worked around by providing a writable directory, like `/tmp/docs/`.

**Comment by astrelsky** [comment]
I believe you may be correct and if you are encountering a permission error then you are. I will change it later to ensure it is within the project's root directory.
