### ISSUE TITLE
Error using `TypeInfo *` in structs

### ISSUE THREAD

**Issue by FlashHit** [astrelsky/Ghidra-Cpp-Class-Analyzer#64]
Check https://github.com/NationalSecurityAgency/ghidra/issues/4578 for more information.

**Comment by astrelsky** [comment]
> Check https://github.com/NationalSecurityAgency/ghidra/issues/4578 for more information.

This type is going to be removed. It was something I had done very early on in the project, well before it was published. This isn't really a DataType and it wasn't supposed to be possible to move it out of the `BuiltinDataTypeManager`.

I'm honestly surprised it took so long for this problem to show up.

**Comment by astrelsky** [comment]
"Fixed" by 187492cd49e1b50c8102bf929138159e9d5085f4

I've simply removed the DataType from the plugin. It was a hack to allow the correct type_info instance to be created in the listing when the type was applied to markup data.
