### ISSUE TITLE
Class analyzer errors while analyzing binary

### ISSUE THREAD

**Issue by Martmists-GH** [astrelsky/Ghidra-Cpp-Class-Analyzer#66]
[application.log](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/files/9657992/application.log)

[Static.elf](https://anonfiles.com/n0a5dfAey9/Static_elf)

**Comment by astrelsky** [comment]
```
2022-09-27 16:10:47 INFO  (AutoAnalysisManager) Analysis Log Messages
Ghidra-Cpp-Class-Analyzer> null

```

Well that's a very informative error log. Might take me a bit to track down but I'll have a look in a bit.

**Comment by astrelsky** [comment]
db474dcd217cb527300906a06d54b8e8c4bfdae4 should fix it. Unfortunately the analyzer doesn't support the rtti in the provided sample. Do you know what compiler was used for this? I have never seen rtti in this format before.

**Comment by Martmists-GH** [comment]
I believe the compiler was ARMCC 4.1, the exact build is unknown.

**Comment by astrelsky** [comment]
> I believe the compiler was ARMCC 4.1, the exact build is unknown. There's also a chance it was built using a proprietary fork of the compiler.

Ok. I definitely won't be able to support that but at least it won't puke an empty message from a NPE anymore.

**Comment by Martmists-GH** [comment]
Where would I start to implement this RTTI format in a fork?

**Comment by astrelsky** [comment]
> Where would I start to implement this RTTI format in a fork?

Unfortunately it would be non-trivial. Due to vast differences here I don't think any of the analysis techniques would be applicable.
